### ISSUE TITLE
[`code` stuff](link) doesn't link

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1276] opened 2018-06-13 04:13 UTC
https://tabatkins.github.io/bikeshed/#dfn-contract shows 

> … a [`lt` attribute]\(#changing-lt) containing one or more pipe-separated …

instead of the expected link.

I've already mentioned this to Tab, but I'm filing it so I notice when it's fixed.

**Comment by tabatkins** [comment] 2018-06-13 18:33
Go subscribe to https://github.com/tabatkins/bikeshed/issues/832, which this is a dupe of. ^_^

**Closed by tabatkins** 2018-06-13 18:33 UTC
