### ISSUE TITLE
[bug] Codeblock inside list has wrong indentation

### ISSUE THREAD

**Issue by gabyx** [tabatkins/bikeshed#2209] opened 2022-01-05 15:05 UTC
Convert the following

```markdown
<pre class='metadata'>
Title: Bla
Shortname: bla
Level: 1
Revision: 1
Status: DREAM
URL:
Markup Shorthands: markdown yes
Editor: 
Date: 2021-01-04
Toggle Diffs: no
No Abstract: no
Default Highlight: cpp
</pre>

# First

-   Bla bla

    ``` cpp
    int a;
    ```
```

Results in

![image](https://user-images.githubusercontent.com/647437/148240171-c60f520f-28e0-4059-ba64-966278f679f8.png)

**Comment by tabatkins** [comment] 2022-01-07 02:13
Indeed, looks like I run the "remove indents from `pre`" code before I do Markdown processing to turn code blocks into `pre`s. It looks like just swapping the order is *mostly* okay, but it causes some paragraphs to lose their paragraph-ness, so I'll have to be play around with this and see how best to handle it.

**Comment by gabyx** [comment] 2022-01-07 08:16
Why not use pandoc ;) and its AST which makes it Commonmark compliant in all means ?

**Comment by tabatkins** [comment] 2022-01-07 19:29
Because Bikeshed-flavored Markdown makes two important changes divergences from CommonMark - no indented code blocks, and good handling of HTML with indentation. (These two are intrinsically connected; you can't do the second without the first.) So no, I can't use any other Markdown parser.

**Comment by gabyx** [comment] 2022-01-07 20:48
Ok jeah, thats true, I also dont understand why indented codeblocks can not be deprecated, its nonsense IMO…

**Comment by gabyx** [comment] 2022-01-07 20:49
Bit I thought the comman mark spec allows HTML everywhere except when its parsed as indented codeblock?

**Comment by tabatkins** [comment] 2022-01-07 21:58
CommonMark does not handle HTML *well*, with proper indentation and such. It fundamentally *can't*, because indented code blocks exist. So you can mix a little HTML into your standard Markdown, but you can't write a proper hybrid HTML/Markdown document, which was explicitly one of my goals with Bikeshed. Thus, Bikeshed-flavored Markdown is slightly different.

The problem here isn't related to any of this, tho. It is indeed just a bug on my part - I just run the indent-removing code before the markdown code blocks are turned into a form that I can recognize as needing their indents removed.

**Comment by gabyx** [comment] 2022-01-07 23:28
Ah thanks for the explanations, interessting. 
No worries, I was just curious. Thanks for the fix :)

**Comment by tabatkins** [comment] 2022-01-13 22:57
All right, took a surprising amount of twiddling before I hit on a correct solution I was happy with. All fixed now, tho.

**Closed** 2022-01-13 22:57 UTC

**Comment by gabyx** [comment] 2022-01-14 12:40
Thanks for your effort!!

**Comment by gabyx** [comment] 2022-01-17 07:38
There is a regression I think:

```markdown
- a:

  \```cpp
  #pragma once

  namespace {
    static const float c_threshold = 3.14156f;
    void myPrivateFunction() {}
  }
  \```
```

Still has wrong indentation. Dont know why.

**Comment by tabatkins** [comment] 2022-01-20 21:59
Ah, it was because you have a blank line in it, which has a *zero*-space prefix. I've now fixed the code to skip blank lines when calculating the prefix to strip, and confirmed that it catches some additional cases in my test files.
