### ISSUE TITLE
IDL interface {{PresentationConnection}} is not autolinking?

### ISSUE THREAD

**Issue by mfoltzgoogle** [tabatkins/bikeshed#1533] opened 2019-10-01 17:41 UTC
In [my spec](https://github.com/webscreens/openscreenprotocol/blob/master/index.bs) i'd like to write just ``{{PresentationConnection}}``, an IDL interface defined in a different spec.

But Bikeshed is unable to resolve the autolink:

> LINK ERROR: No 'idl' refs found for 'PresentationConnection'.
{{PresentationConnection}}
LINK ERROR: No 'idl' refs found for 'PresentationConnection'.
{{PresentationConnection|PresentationConnections}}
==============DONE==============

Specref can resolve it successfully:

```bash
$ bikeshed refs --text="PresentationConnection"
status:      anchor-block
for:         []
level:       
url:         https://w3c.github.io/presentation-api/#presentationconnection
text:        PresentationConnection
linkingText: PresentationConnection
export:      True
shortname:   presentation-api
type:        interface
spec:        presentation-api
```

I've tried manually specifying the spec attribute, but it doesn't seem to help.  Do I need to do anything else to import this definition from presentation-api?

**Comment by tabatkins** [comment] 2019-10-01 18:18
Hm, I loaded up the OpenScreenProtocol source file locally, inserted a `{{PresentationConnection}}` autolink, and processed it, and it successfully linked.  Can you give me a source file that's failing for you?

**Comment by tabatkins** [comment] 2019-10-16 23:57
ping?

**Comment by garykac** [comment] 2020-03-03 01:08
Not sure if it's the same issue or not, but I'm having a similar problem getting `{{PointerEvent}}` to link in the [UIEvents](https://github.com/w3c/uievents) spec.

> LINK ERROR: No 'idl' refs found for 'PointerEvent'.
> {{PointerEvent}}

@NavidZ is also encountering this problem. We've run `bikeshed update` but are still seeing this issue.

AFAICT, the PointerEvents spec is properly included in [SpecRef](https://www.specref.org/?q=PointerEvents)

Any suggestions for how to troubleshoot this?  Thanks!

**Comment by domenic** [comment] 2020-03-03 01:43
This is likely because pointer events is a ReSpec spec, which does not work with autolinking. Instead you need to manually construct anchor blocks.

**Comment by tabatkins** [comment] 2020-03-03 22:10
Nah, it's not linkable because it's not in the anchor db. (You can search in <https://github.com/tabatkins/bikeshed/blob/master/bikeshed/spec-data/readonly/specs.json>.)

That said, since I just added it, I'll only get the /TR version, not the ED, for that reason - Bikeshed's spider looks at the source, and so "live" ReSpec documents are completely unusable unless the author does a ton of manual attribute-writing themselves.

(Plan is to move the spidering tool over to Reffy, which uses a headless Chromium to render the document before spidering, and so "live" ReSpec documents will work. But until then, no luck.)

**Comment by tabatkins** [comment] 2020-03-03 22:11
@mfoltzgoogle By the way, ping still on your issue? I couldn't reproduce, could you either give me a source file that fails or let me know I can close this?

**Comment by tabatkins** [comment] 2020-03-19 16:52
Gonna close this, as presumably Mark solved his issue that I could never reproduce.

**Closed by tabatkins** 2020-03-19 16:52 UTC
