### ISSUE TITLE
Feature: Link from definitions to all uses

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#469] opened 2015-08-26 20:55 UTC
It's very nice in the HTML spec to be able to click on a definition like https://html.spec.whatwg.org/multipage/browsers.html#browsing-context and see all the uses. Bikeshed should support the same thing, at least within a single spec, and possibly across specs in Shepherd.

**Comment by domenic** [comment] 2015-08-26 21:02
This would basically amount to including `<script src="https://resources.whatwg.org/dfn.js" async></script>` in your template, right?

**Comment by tabatkins** [comment] 2015-08-27 04:47
Lol, why does that script only check three levels up for "no-backref", that's ridiculous.

I'm happy to support this as a standard feature and just inline that script.

**Comment by domenic** [comment] 2015-08-27 04:49
No more inlining please.. Way too much stuff is render-blocking and uncacheable in my Bikeshed specs already.

**Comment by tabatkins** [comment] 2015-08-27 05:23
I inline because I'm not super-comfortable with having random specs across the internet gain external dependencies they didn't expect.  I'm happy to try and make things better, tho.  What's currently in WHATWG specs that is bothering you?  All I can see that isn't content or the WHATWG boilerplate is the highlighting styles, which are a tiny block.  (Maybe take this to a separate bug.)

**Comment by tabatkins** [comment] 2016-02-20 00:13
So I just committed a statically-generated version of dfn.js into Bikeshed.  For now it's behind a pref - if you set `Use Dfn Panels: yes`, it'll generate dfn panels a la dfn.js.  This feature replaces self-links on dfns; a dfn that isn't referenced anywhere will continue to generate a self-link as normal.

Try it out and let me know what you think!  If it's good I'll pref it on by default (and pref it off in WHATWG's defaults until they move off of dfn.js generally).

**Closed by tabatkins** 2016-02-20 00:13 UTC

**Comment by jyasskin** [comment] 2016-02-20 01:35
This is great, thanks! Some issues:

* https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#characteristic-properties has a weird bullet saying:

  > 5.4.1. BluetoothCharacteristicProperties#bluetoothcharacteristicpropertiesReferenced in:5.1. GATT Information Model5.4. BluetoothRemoteGATTCharacteristic5.4.1. BluetoothCharacteristicProperties (2) (3) (2) (3)
* https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#characteristic-descriptors lost the numbering on its `<li>`s.
* https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#discover-all-primary-services has a self-link instead of a definition panel? I think this happens when a definition has no uses in the same document. (In this case, that means I ought to remove that definition, but that's not always true.)
* https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#bluetoothremotegattcharacteristic doesn't have a definition panel.

**Comment by jyasskin** [comment] 2016-02-20 01:37
* https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#dom-bluetooth-requestdevice has a link whose text is "9. Terminology and Conventions", but which links into [1.1 Examples](https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#introduction-examples).

**Comment by domenic** [comment] 2016-02-20 01:39
Mobile styling could also use some work. I'm thinking position fixed, height 50vh, bottom of the screen, width 100vw, only a top border?

**Comment by mkruisselbrink** [comment] 2016-02-20 04:38
Tried it on the service worker spec, and similar to what @jyasskin mentioned all links for usage seem to link to the first usage of the definition. So even though it might list the correct usages they all link to the same target.

**Comment by tabatkins** [comment] 2016-02-22 22:34
> https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#characteristic-properties has a weird bullet saying:

The heading being referenced has a `<dfn>` which had already gotten its dfn-panel added, so when I asked for its textContent, it got the text of the dfn-panel too.  Fixed to now extract just the text I actually want. ^_^ 

> https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#characteristic-descriptors lost the numbering on its <li>s.

Markup error on your part - that sublist is now a series of `<ol>`s with no `<li>`s in your source document.  Do you auto-gen that somehow?

> https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#discover-all-primary-services has a self-link instead of a definition panel? That one has no uses,

Yup, if there's no refs I drop back to generating a self-link.

> but https://webbluetoothcg.github.io/web-bluetooth/#dom-requestdeviceoptions-optionalservices does and also doesn't have a panel.

If I generate from your source, it has a dfn panel correctly showing both references.  How weird.  Let me know if it's still doing that.

> https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#bluetoothremotegattcharacteristic doesn't have a definition panel.

Ah, I wasn't adding panels to headings that are definition sources.  Fixed.

> https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#dom-bluetooth-requestdevice has a link whose text is "9. Terminology and Conventions", but which links into 1.1 Examples.

Whoops, was accidentally setting IDs with just the dfn's id and the index of the reference *in that section*. So there were a lot of duplicate IDs in the document, and anchor refs always go to the first.  Fixed now.

Thank you so much for trying it out and reporting these issues!

**Comment by tabatkins** [comment] 2016-02-22 22:57
> Mobile styling could also use some work. I'm thinking position fixed, max-height 50vh (with overflow auto), bottom of the screen, width 100vw, only a top border?

After playing with this a bit, I kinda like it better in general this way, so I've made it always bottom-attached. Let me know how it feels?

**Comment by jyasskin** [comment] 2016-02-23 00:03
Oops at the missing `<li>`s. Those are [fixed](https://github.com/WebBluetoothCG/web-bluetooth/tree/dfn-panels) now.

Everything else looks fixed; thanks! One feature request: could you keep the panel showing after I click something in it? It's helpful in the HTML spec to be able to browse through a bunch of uses by just clicking a bunch of times on the panel.

**Comment by domenic** [comment] 2016-02-23 00:09
> After playing with this a bit, I kinda like it better in general this way, so I've made it always bottom-attached. Let me know how it feels?

Seems pretty bad. I have to move my mouse all the way to the bottom of the screen?

Also, the width seems artificially restricted, in Firefox at least; see e.g. https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#supported-physical-transports where the header becomes "#supported-physical-trans-\nports", or https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#bluetooth-device where a "(2)" spills to the next line.

Also it'd be good to add cursor: pointer to the dfns.

**Comment by tabatkins** [comment] 2016-02-23 00:33
> Seems pretty bad. I have to move my mouse all the way to the bottom of the screen?
That was my fear, but after using the other way a bit, it has the potential to be off-screen too, if the definition is sufficiently close to the end of the line.  If you're okay with this, I can change it back and just do the fixpos on small screens.

Note, though, the interaction with Jeffrey's request that it stay up on the screen - if I do that, only fixpos makes sense.

> Also, the width seems artificially restricted, in Firefox at least; 

Wtf Firefox, I'm using `width: fit-content`, which is "as wide as you want, maxed at your container width", same as floats. If this is messing up, it's a Firefox bug. :/

> Also it'd be good to add cursor: pointer to the dfns.

Sure. Doing so now.

> One feature request: could you keep the panel showing after I click something in it? It's helpful in the HTML spec to be able to browse through a bunch of uses by just clicking a bunch of times on the panel.

Makes sense - I was basing the interactions off of dfn.js's behavior. What should trigger it to close, tho?  Maybe I can add a "dock" toggle, which'll make everyone happy - it'll normally show up near the dfn, and go away when you click, but if you dock it it'll stay open forever until you close it, so you can click multiple references, and even navigate around the document further, without losing it.

**Comment by jyasskin** [comment] 2016-02-23 00:54
https://dom.spec.whatwg.org/#concept-element opens the panel next to the dfn element. If I click a use, the panel moves to the bottom-left and stays open. If I click outside the panel, it closes. I don't have a strong preference between this and a 'dock' toggle.

**Comment by tabatkins** [comment] 2016-02-23 01:11
...huh, I didn't realize it did that.  I just put that behavior together, and it works really nicely.  So now I've switched it back to hovering near the definition by default (docked to the bottom on small screens), and then auto-docking to the corner once you click a link, closing when you click elsewhere.

I still need to test this on a mobile device; at the moment I'm guessing about the behavior.

**Comment by tabatkins** [comment] 2016-02-23 17:12
Okay, unless one of y'all says otherwise, I'm going to turn on dfn-panels by default later today.  domenic, I'll remove the dfn.js script from the WHATWG header.  That cool?

**Comment by domenic** [comment] 2016-02-23 22:56
@tabatkins I'd prefer you not do the switch until you have a fix or workaround for the layout in Firefox.

**Comment by domenic** [comment] 2016-02-23 22:57
@tabatkins just tested on mobile (using Web Bluetooth) and it looks good until you click on the dfn. When you do the panel jumps up and over a few pixels and looks pretty strange.

**Comment by domenic** [comment] 2016-02-23 22:59
Oh hmm it doesn't work on mobile Chrome at all (I was testing mobile Firefox); the panel is totally off-screen.

**Comment by tabatkins** [comment] 2016-02-23 23:46
> I'd prefer you not do the switch until you have a fix or workaround for the layout in Firefox.

This isn't even a Firefox issue - I noticed it in Chrome too. It looks like sometimes there're a pixel off when calculating intrinsic sizes.

Looking at dfn.js, it appears that it just allows them to be any width whatsoever, with no max-width.  I guess I can duplicate that; the current CSS is just attempting to prevent them from growing ridic wide. Sucks that browsers are slightly buggy here. :/

> Oh hmm it doesn't work on mobile Chrome at all (I was testing mobile Firefox); the panel is totally off-screen.

While I'll definitely do more testing, *I'm almost exactly reproducing the current dfn.js behavior*. So whatever's fucked up with it, it's fucked up in the WHATWG specs **right now**.

**Comment by domenic** [comment] 2016-02-23 23:57
> While I'll definitely do more testing, I'm almost exactly reproducing the current dfn.js behavior. So whatever's fucked up with it, it's fucked up in the WHATWG specs right now.

That's not true; you've changed the mobile styling. Previously it was a bit meh on mobile Chrome. Now it is unusable on mobile Chrome (since it is completely offscreen).

**Comment by tabatkins** [comment] 2016-02-24 00:58
> Now it is unusable on mobile Chrome (since it is completely offscreen).

Hm, trying it on my own, it works perfectly fine on mobile Chrome.  Unless maybe you have a messed up meta-viewport?  What spec are you seeing the problems on?

**Comment by tabatkins** [comment] 2016-02-24 01:00
(And I mean, the web is the worst, but I don't see any way the "default mobile behavior" should mess up worse than the "dock upon click" behavior, as they're both "position:fixed to somewhere around the bottom of the screen.)

**Comment by domenic** [comment] 2016-02-24 01:02
Try clicking on "Advertising Data" in Web Bluetooth

**Comment by tabatkins** [comment] 2016-02-24 01:14
Ugh, ffs, this is a result of the mobile viewport *still* being messed up.  It looks like, if there is an element wider than the default viewport, the pos:fixed viewport is set to that width, with the screen's normal aspect ratio, so it's actually taller than the screen. ://///////

**Comment by tabatkins** [comment] 2016-02-24 01:16
(In other words, this still means dfn.js is just as messed up - it exhibits the exact same crappy behavior once you "dock" it by clicking on one of the links.)

**Comment by tabatkins** [comment] 2016-02-24 01:21
I can just remove the mobile behavior again, so my behavior is identical to current dfn.js.  I don't think it's reasonable to hold up deployment of this if it's *no worse* than current dfn.js behavior.  It should ideally be *better*, but if the alternative is that people deploy dfn.js with the exact same busted behavior, eh.

**Comment by domenic** [comment] 2016-02-24 01:45
I'd still prefer to stick with dfn.js for WHATWG specs until we've got the behavior worked out. We can more easily tweak dfn.js than we can PR Bikeshed, wait for you to accept, then re-build our specs.

**Comment by tabatkins** [comment] 2016-02-24 01:48
That's fine, I can pref the panels off for WHATWG until y'all are ready to switch. It's just a line in `defaults-whatwg.include`.  But I'd like to turn this on for everyone else.

**Comment by tabatkins** [comment] 2016-02-27 00:28
And done. I've removed the mobile styling for now, and turned the panels on by default.  WHATWG currently has them preffed off by default.  Let me know what tweaks y'all make to dfn.js to handle mobile styling better!
