### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'dict_values' and 'list'

### ISSUE THREAD

**Issue by coolbrg** [tabatkins/bikeshed#1576] opened 2019-12-27 10:46 UTC
Hi,

I have followed the install guide for macOS as mentioned here https://tabatkins.github.io/bikeshed/#install-homebrew

I am hit by the following error:
```
(bikeshed) ✘-1 ~/me/osproj/bikeshed [master|…511]
16:14 $ bikeshed update
Traceback (most recent call last):
  File "/usr/local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/coolbrg/me/osproj/bikeshed/bikeshed/__init__.py", line 4, in <module>
    from .cli import main
  File "/Users/coolbrg/me/osproj/bikeshed/bikeshed/cli.py", line 8, in <module>
    from . import config
  File "/Users/coolbrg/me/osproj/bikeshed/bikeshed/config/__init__.py", line 5, in <module>
    from .dfnTypes import *
  File "/Users/coolbrg/me/osproj/bikeshed/bikeshed/config/dfnTypes.py", line 50, in <module>
    dfnTypes = frozenset(dfnClassToType.values() + ["dfn"])
TypeError: unsupported operand type(s) for +: 'dict_values' and 'list'
```

```
$ git log -n 1
commit 087ea90e1ebd0321c20373d89950d1c6b73d5df1 (HEAD -> master, origin/master, origin/HEAD)
Author: François Daoust <fd@tidoust.net>
...
```

Let me know if any other info is needed.

**Comment by tabatkins** [comment] 2019-12-27 14:20
So hm, the base problem here is clearly that it's trying to execute Bikeshed with Python 3, which it doesn't yet support.

I'll have to dig around to see why it's doing so.

**Comment by vapier** [comment] 2019-12-29 07:28
should dupe into #1138

**Comment by tabatkins** [comment] 2019-12-29 07:33
Not really. The underlying problem is that something in the install process
is not specifying Python 2. Once I update Bikeshed I suppose this will be
fixed, but it should be fixable before that.

(I'm still on vacation for another week.)

**Comment by vapier** [comment] 2019-12-29 07:49
that's a user local/distro issue, not a problem with bikeshed itself.  the problem with bikeshed is that it doesn't support Python 3 which is a dupe of that issue.

depending on the distro, they might be able to force Python 2 specific install with `pip2` rather than `pip`.  but there's nothing bikeshed can do other than finally port to Python 3.

**Comment by tabatkins** [comment] 2019-12-29 17:43
> that's a user local/distro issue, not a problem with bikeshed itself. the problem with bikeshed is that it doesn't support Python 3 which is a dupe of that issue.

If the install instructions, faithfully followed, produce an error, that's a problem with Bikeshed. Stop disagreeing with me about whether or not something is a problem with my own project. ^_^

**Comment by tabatkins** [comment] 2020-03-21 00:19
Closing because Bikeshed is now on py3, and this is no longer a problem.

**Closed by tabatkins** 2020-03-21 00:19 UTC
