### ISSUE TITLE
Linking to the new constructor() syntax is hard

### ISSUE THREAD

**Issue by birtles** [tabatkins/bikeshed#1530] opened 2019-09-24 06:02 UTC
I've been converting Web Animations over to the new constructor syntax but I find that linking to these new constructors often doesn't work. For example:

```
<pre class='idl'>
[Exposed=Window]
interface Yer {
  constructor();
  constructor(double a);
};
</pre>

<div class=constructors>

:   <dfn constructor for=Yer lt="constructor()">Yer ()</dfn>
::  Creates a new {{Yer}}.

:   <dfn constructor for=Yer lt="constructor(a)">Yer (a)</dfn>
::  Creates a new {{Yer}} with an <emphasis>a</<emphasis>.

</div>

Note: {{Yer/constructor(a)}} works but is not very helpful. It prints "constructor(a)", but which constructor?

Note: {{Yer(a)}} sometimes appears to work but actually links somewhere
completely different.

Note: {{Yer(a)|Yer}} has the same problem.

Note: <a constructor for=Yer lt="Yer(a)">Yer(a)</a> too.

Note: <a constructor for=Yer lt="constructor(a)">Yer(a)</a> is what you really
want but is a lot more to type (and doesn't get the monospace styles that you
get with the curly brace syntax).
```

I've been applying the latter syntax but it's a bit tedious, makes the source harder to read/maintain, and I'm not confident I've found all the instances. It would be nice if the old syntax would keep working.

**Comment by tabatkins** [comment] 2019-09-24 06:13
Ooh, I should definitely auto fix the default tex display text of a constructor() link to say the interface instead, yeah.

Where is Yer() linking to?

**Comment by birtles** [comment] 2019-09-24 06:22
Regarding the middle three cases, it's odd, but in Web Animations when the equivalent links end up pointing to an _absolute URL_: https://drafts.csswg.org/web-animations-1/#dom-yer-yer but when I tried to create a minimized test case it just complained the links were invalid.

Also, I'm pretty sure I found that when linking to constructor arguments I had to use `Yer/constructor(a)/a` and couldn't use `Yer/Yer(a)/a`. It's no big deal but if we want to say `Yer/Yer(a)` and `Yer/constructor(a)` are equivalent we should probably allow either.

**Comment by birtles** [comment] 2019-09-24 06:24
> Where is Yer() linking to?

For `{{Yer()}}` I get `LINK ERROR: No 'idl' refs found for 'Yer()'`

**Comment by birtles** [comment] 2019-09-30 12:32
For what it's worth, this is still blocking updating a number of specs to the new constructor syntax. (Not meaning to nag, just mentioning it in case it helps with prioritization.)

**Comment by tabatkins** [comment] 2019-09-30 22:05
Okay, so the issue here is that Bikeshed, when generating the `lt` for IDL definitions, generates all the linking variants automatically.  For `constructor()`, it adds `lt="constructor() | Foo()"`; if there are optional arguments, it adds more variants, etc.

If you provide your own definition, it doesn't do this. It auto-detects that you've defined your constructor, links the IDL to that, and then that's that. So if you didn't define all the variants yourself, you can use those variants to autolink.

(This happens with normal methods too, it's just not run into as commonly, since I *do* magically handle the no-arg case when autolinking as long as it's unambiguous. You'd only see it if you had optional arguments and you tried to autolink with a "shorter" form than what you used in the `<dfn>`.)

I've been meaning to find a solution to this for a while anyway, it just hasn't been high priority since it's rarely relevant in methods. I'll bump it up and fix it this week.

**Comment by tabatkins** [comment] 2019-10-01 01:05
All right, should be fixed! My solution's a little hacky, so I'm surprised it worked as well as it did, but it appears that nothing's broken across the entire regression testsuite from this, merely improved!

So now what happens is, if you have an IDL block in your spec, and manually define one of the values from that block, it'll copy over all the "smart" `lt` values from the IDL definition over to your manual one.

So, for example:

```html
<pre class='idl'>
[Exposed=Window]
interface Foo {
  constructor();
  constructor(double a, optional double b);
};
</pre>

The <dfn for=Foo constructor>Foo (a)</dfn> constructor...
```

will automatically set `lt="Foo(a, b)|constructor(a, b)|Foo(a)|constructor(a)"` on the manual `dfn`, and auto-linking will then work with any of the forms.

(This also works with enum values, which is great!)

**Closed by tabatkins** 2019-10-01 01:05 UTC

**Comment by birtles** [comment] 2019-10-01 04:33
Seems to work perfectly. Thank you!
