### ISSUE TITLE
WD generation has lots of unnecessary links to EDs

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#1070] opened 2017-08-15 20:03 UTC
Was regenerating CSS3 Text for WD publication, and had to do a lot of manual cleanup. Things like combinators linking to the ED of values and units L4 for no apparent reason (when there's a perfectly acceptable definition in L3), "inline base direction" also linking to the ED of css-writing-modes-4 instead of css-writing-modes-3, various terms linking to ED of css-cascade-4 (even though css-cascade-4 is CR on /TR).

**Comment by tabatkins** [comment] 2017-08-15 20:20
I thought I'd documented this problem already, but yeah, it's known - the "only pay attention to the latest version" code doesn't care about the current/snapshot distinction, and if you have a level N+1 current spec but only have snapshots for level N, the level N links will get ignored early.  I need to fix this.

> various terms linking to ED of css-cascade-4 (even though css-cascade-4 is CR on /TR).

This is something new, tho, can you provide an example of it?

**Comment by fantasai** [comment] 2017-08-15 20:43
Cascade 4: https://drafts.csswg.org/css-text/#index-defined-elsewhere 'inherit', 'shorthand', 'shorthand property' all link to the ED.

**Comment by tabatkins** [comment] 2017-09-20 23:59
Fixed - it was a Shepherd issue.

Debugging guidance, for future reference: ran `bikeshed refs --text="inherit" --type="value"`, only got a single result, for the ED.  Checked the TR version, saw the dfn is definitely marked up correctly.  Checked Shepherd, saw that Cascade 4 has only a "draft" url.  Fixed. ^_^

**Comment by tabatkins** [comment] 2017-09-21 00:04
Well, fixed the latter, more confusing issue. Working on the former issue. ^_^

**Comment by tabatkins** [comment] 2017-09-21 00:57
...found the fucking bug. This Enum library is bullshit and it should never have existed.  The bug is that, somehow, `"current" == config.refStatus.snapshot` is returning `True`.  It doesn't *always* return true; if you compare it with a string that's not in the enum at all, it returns false. But it somehow always compares true if the string is in the enum at all, regardless of which enum value you're comparing it to.

**Comment by tabatkins** [comment] 2017-09-22 20:13
All right, should be fixed now - I confirmed that Text 3 now links only to V&U 3 and Writing Modes 3, since all of its references exist there in snapshot specs.

**Closed** 2017-09-22 20:12 UTC
Labels: bug

**Comment by fantasai** [comment] 2017-09-27 17:33
Yay, thanks!

Wrt Shepherd issue, can you confirm if Ruby has the same problem? I'm getting links to the ED on that one, too. (searching for ''collapse'')

**Comment by tabatkins** [comment] 2017-09-27 17:53
No, Ruby is in there, tho the latest draft is from 2014 <https://www.w3.org/TR/css-ruby-1/>

**Comment by tabatkins** [comment] 2017-09-30 21:57
Responding here for posterity - the TR Ruby draft has some weird `title` attributes on its value definitions that is preventing them from getting autolinked properly.
