### ISSUE TITLE
FATAL ERROR: Multiple local <dfn>s have the same linking text

### ISSUE THREAD

**Issue by beaufortfrancois** [tabatkins/bikeshed#1536] opened 2019-10-09 08:03 UTC
Code below used to work. It doesn't anymore. I suspect https://github.com/tabatkins/bikeshed/commit/d286255e48022dd681a447e0b73791ec5691878f is the culprit.
Hopefully it helps

```
<script type=idl>
interface Interface {
    attribute object foo;
};
</script>

<dl dfn-type=attribute dfn-for=Interface>
    : <dfn>foo</dfn>
    ::
        Text
</dl>
```

```
FATAL ERROR: Multiple local 'attribute' <dfn>s for 'Interface' have the same linking text 'foo'.
 ✘ Did not generate, due to fatal errors
```

**Comment by Ms2ger** [comment] 2019-10-09 08:05
Also broke WebIDL.

**Comment by tabatkins** [comment] 2019-10-09 22:39
So this is weird! The fatal errors *do not* affect the output, somehow - this is how I missed it, because the test suite still passes.

I'm trying to figure it out; I'm gonna go ahead and revert the changes that caused this, because they're refactoring and not crucial. I suspect they're a lingering result of some changes I made earlier, being suddenly exposed by an unrelated change.

**Comment by tabatkins** [comment] 2019-10-09 23:09
Anyway, reverted on master, I'll continue to research the issue on a branch. Should be fixed.

**Closed by tabatkins** 2019-10-09 23:09 UTC

**Comment by Ms2ger** [comment] 2019-10-10 07:48
Still broken here. Did you push?

**Comment by beaufortfrancois** [comment] 2019-10-10 09:27
+1 to @Ms2ger. I can still reproduce.

**Comment by tabatkins** [comment] 2019-10-10 15:55
ARGH I didn't realize how `git revert` worked; I thought it would revert all the commits up to the one I chose, not just the single one I chose.

ANYWAY, fixed now on master, and confirmed personally.
