### ISSUE TITLE
New WebIDL constructor operation breaks links

### ISSUE THREAD

**Issue by dirkschulze** [tabatkins/bikeshed#1521] opened 2019-09-16 18:38 UTC
I replaced the `Constructor` extended attribute with the new constructor operation in the Geometry spec: https://github.com/w3c/fxtf-drafts/pull/373 for all interfaces from:
```
[Constructor(optional unrestricted double x = 0, optional unrestricted double y = 0,
             optional unrestricted double z = 0, optional unrestricted double w = 1),
 Exposed=(Window,Worker),
 Serializable]
interface DOMPointReadOnly {
    [NewObject] static DOMPointReadOnly fromPoint(optional DOMPointInit other = {});

    readonly attribute unrestricted double x;
    readonly attribute unrestricted double y;
    readonly attribute unrestricted double z;
    readonly attribute unrestricted double w;

    [NewObject] DOMPoint matrixTransform(optional DOMMatrixInit matrix = {});

    [Default] object toJSON();
};

[Constructor(optional unrestricted double x = 0, optional unrestricted double y = 0,
             optional unrestricted double z = 0, optional unrestricted double w = 1),
 Exposed=(Window,Worker),
 Serializable,
 LegacyWindowAlias=SVGPoint]
interface DOMPoint : DOMPointReadOnly {
    [NewObject] static DOMPoint fromPoint(optional DOMPointInit other = {});

    inherit attribute unrestricted double x;
    inherit attribute unrestricted double y;
    inherit attribute unrestricted double z;
    inherit attribute unrestricted double w;
};
```

to

```
[Exposed=(Window,Worker),
 Serializable]
interface DOMPointReadOnly {
    constructor(optional unrestricted double x = 0, optional unrestricted double y = 0,
            optional unrestricted double z = 0, optional unrestricted double w = 1);

    [NewObject] static DOMPointReadOnly fromPoint(optional DOMPointInit other = {});

    readonly attribute unrestricted double x;
    readonly attribute unrestricted double y;
    readonly attribute unrestricted double z;
    readonly attribute unrestricted double w;

    [NewObject] DOMPoint matrixTransform(optional DOMMatrixInit matrix = {});

    [Default] object toJSON();
};

[Exposed=(Window,Worker),
 Serializable,
 LegacyWindowAlias=SVGPoint]
interface DOMPoint : DOMPointReadOnly {
    constructor(optional unrestricted double x = 0, optional unrestricted double y = 0,
            optional unrestricted double z = 0, optional unrestricted double w = 1);

    [NewObject] static DOMPoint fromPoint(optional DOMPointInit other = {});

    inherit attribute unrestricted double x;
    inherit attribute unrestricted double y;
    inherit attribute unrestricted double z;
    inherit attribute unrestricted double w;
};
```

The attributes `x`, `y`, `z` and `w` are defined with:

```xml
<div dfn-type=attribute dfn-for="DOMPointReadOnly, DOMPoint">
    The <dfn><code>x</code></dfn> attribute, on getting, must return the <a for=point>x
    coordinate</a> value. For the {{DOMPoint}} interface, setting the
    {{DOMPoint/x}} attribute must set the <a for=point>x coordinate</a> to the new value.

    The <dfn><code>y</code></dfn> attribute, on getting, must return the <a for=point>y
    coordinate</a> value. For the {{DOMPoint}} interface, setting the
    {{DOMPoint/y}} attribute must set the <a for=point>y coordinate</a> to the new value.

    The <dfn><code>z</code></dfn> attribute, on getting, must return the <a for=point>z
    coordinate</a> value. For the {{DOMPoint}} interface, setting the
    {{DOMPoint/z}} attribute must set the <a for=point>z coordinate</a> to the new value.

    The <dfn><code>w</code></dfn> attribute, on getting, must return the <a for=point>w
    perspective</a> value. For the {{DOMPoint}} interface, setting the
    {{DOMPoint/w}} attribute must set the <a for=point>w perspective</a> to the new value.
</div>
```

Now all attributes start linking to the arguments of the `DOMPoint` constructor instead of their definitions and I get the following errors:

```
WARNING: Multiple elements have the same ID 'dom-domrectreadonly-y'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domrectreadonly-x'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domrectreadonly-height'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domrect-y'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domrect-x'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-dompointreadonly-x'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-dompointreadonly-y'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-dompointreadonly-z'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-dompointreadonly-w'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domquad-p1'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domquad-p3'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domquad-p2'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domquad-p4'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domrect-height'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domrectreadonly-width'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-domrect-width'.
Deduping, but this ID may not be stable across revisions.
LINK ERROR: Multiple possible 'idl' local refs for 'x'.
Arbitrarily chose the one with type 'attribute' and for 'DOMPoint' or 'DOMPointReadOnly'.
{{DOMPoint/x}}
LINK ERROR: Multiple possible 'idl' local refs for 'y'.
Arbitrarily chose the one with type 'attribute' and for 'DOMPoint' or 'DOMPointReadOnly'.
{{DOMPoint/y}}
LINK ERROR: Multiple possible 'idl' local refs for 'z'.
Arbitrarily chose the one with type 'attribute' and for 'DOMPoint' or 'DOMPointReadOnly'.
{{DOMPoint/z}}
LINK ERROR: Multiple possible 'idl' local refs for 'w'.
Arbitrarily chose the one with type 'attribute' and for 'DOMPoint' or 'DOMPointReadOnly'.
{{DOMPoint/w}}
LINK ERROR: Multiple possible 'idl' local refs for 'x'.
Arbitrarily chose the one with type 'argument' and for 'DOMRect'.
{{DOMRect/x}}
LINK ERROR: Multiple possible 'idl' local refs for 'y'.
Arbitrarily chose the one with type 'argument' and for 'DOMRect'.
{{DOMRect/y}}
LINK ERROR: Multiple possible 'idl' local refs for 'width'.
Arbitrarily chose the one with type 'argument' and for 'DOMRect'.
{{DOMRect/width}}
LINK ERROR: Multiple possible 'idl' local refs for 'height'.
Arbitrarily chose the one with type 'argument' and for 'DOMRect'.
{{DOMRect/height}}
 ✔  Successfully generated, with 8 linking errors
```

**Comment by tabatkins** [comment] 2019-09-17 07:08
Yup, dupe of #1519. I need to make Bikeshed aware of the new constructor method. Haven't been able to due to TPAC/etc.

**Closed by tabatkins** 2019-09-17 07:08 UTC

**Comment by dirkschulze** [comment] 2019-09-17 07:30
Ah yes! Thanks.
