### ISSUE TITLE
Anchor links on mobile go to the wrong place

### ISSUE THREAD

**Issue by BRevzin** [tabatkins/bikeshed#1485] opened 2019-06-04 17:06 UTC
[Here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0847r2.html) is a paper I wrote using bikeshed. If you load it on mobile and start clicking on the links (either the table of contents links or the self-links next to the sections), they don't... quite go to where they're supposed to. Some of them work sometimes, others target somewhere _later_ than where they're supposed to go. For instance, clicking on 4.4.2 from the table of contents takes me nearly to 4.5.

There's something about the `<meta name="viewport" >` tag that causes these links to do weird things, but I am not familiar enough with any web technology to do offer more than that.

**Comment by tabatkins** [comment] 2019-06-05 13:23
Woah, weird. This looks like a browser bug? It's just an anchor link, and the anchors are in the headings, right where you'd expect. If the navigation isn't scrolling to them, that's messed up on the browser side.

I can reproduce this in modern Android Chrome, but it doesn't reproduce in iOS browser. I'll report this on Chrome, thanks for the notice.

I'll go ahead and close this tho, as there's nothing Bikeshed can really do, I think.

**Closed by tabatkins** 2019-06-05 13:23 UTC

**Comment by tabatkins** [comment] 2019-06-05 13:24
(By the way, I recently pushed an update to Bikeshed's styling that should make large tables render better. Where's the source for your paper? I'd like to test that it works properly on your code-example blocks.)

**Comment by tabatkins** [comment] 2019-06-05 13:29
Filed at <https://bugs.chromium.org/p/chromium/issues/detail?id=971237>

**Comment by BRevzin** [comment] 2019-06-05 13:41
Thanks! Honestly, I'm glad it's a browser issue -- that seems saner than any kind of explanation where direct links to ids don't work... 

The source for that paper is: https://github.com/BRevzin/cpp_proposals/blob/master/0847_deducing_this/deducing-this.bs
