### ISSUE TITLE
Would like a nicer way to link to HTTP headers

### ISSUE THREAD

**Issue by cbiesinger** [tabatkins/bikeshed#2220] opened 2022-01-28 20:50 UTC
Right now I can link to something like [[RFC7231#header.referer|Referer]], but that requires me to know which spec it's defined in. It would be nice if there was an automatic syntax similar to DOM and CSS properties, ideally it also supports other specs that define headers (such as https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-strict-origin)

**Comment by tabatkins** [comment] 2022-02-04 19:38
Closing as a dupe of #1492, but I should actually do what I proposed in #1492 then. ^_^

**Closed by tabatkins** 2022-02-04 19:38 UTC
