### ISSUE TITLE
Allow "non-normative definitions"

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#960] opened 2017-03-20 20:22 UTC
For Infra, we would like to have an example that defines a concept, but only for the purposes of that example. Such as:

```html
<div class=example id=example-tuple>
 <p>A <dfn>status</dfn> is an example <a>tuple</a> consisting of a <dfn for=status>code</dfn>
 (a three-digit number) and <dfn for=status>text</dfn> (a byte sequence).

 <p>A nonsense algorithm that manipulates <a>status</a> tuples for the purpose of demonstrating
 their usage is then:</p>

 <ol>
  <li>Let |statusInstance| be (<a for=status>code</a>: 200, <a for=status>text</a>: `<code>OK</code>`).
  <li>Set |statusInstance| to (301, `<code>DOES NOT MATTER</code>`).
  <li>If |statusInstance|'s <a for=status>code</code> is 404, then &hellip;
 </ol>
</div>
```

The biggest thing I guess is making sure it doesn't end up in an index. A bonus would be if the concept was never exported even if people did spec=infra or similar. Maybe there are other considerations.

**Comment by tabatkins** [comment] 2017-03-28 22:02
I'm inclined to reject this, because really it just seems like you want the styling of a dfn/link on example text, right?  You can achieve that yourself just by using CSS, then.  Adding a new "dfn, but only accessible to autolinks present inside the same example container" would be pretty complicated to mesh into the current autolinking code.

**Comment by domenic** [comment] 2017-03-29 01:15
Hmm, that's a fair point. I think they're still semantically `<dfn>`s, but that doesn't really matter... I guess it suggests a `<dfn nomagic>` or similar, which Bikeshed simply does nothing with (besides strip the attribute). Then you have to manually use `<a href="#id">` instead of autolinks, which is totally fine.

**Comment by domenic** [comment] 2020-07-23 20:18
Bump. I'd like to use this to specify https://github.com/whatwg/infra/issues/92, which needs a series of examples. In particular I don't want the examples to show up inside https://infra.spec.whatwg.org/#index-defined-here, or get dfn panels, or anything. I just want them to use the correct semantic markup.

`<dfn ignore>` is another potential name.

**Comment by tabatkins** [comment] 2020-07-24 22:29
Yeah, `<dfn ignore>` makes sense. I made the simplest possible change for this, that I'm pretty sure should work; let me know if you're getting dfns being recognized in some places anyway.

**Comment by domenic** [comment] 2020-07-27 17:09
When I tried this I got the following error:

```
Error running preprocessor, returned code: 2.
WARNING: Unexported dfn that's not referenced locally - did you mean to export it?
&lt;dfn data-var-ignore="" data-dfn-type="dfn" id="algorithm-name" data-lt="[algorithm name]" data-noexport="by-default">[algorithm name]&lt;a href="#algorithm-name" class="self-link">&lt;/a>&lt;/dfn>
 ✘  Did not generate, due to fatal errors
```

**Comment by tabatkins** [comment] 2020-07-27 19:31
Ah, indeed, I can reproduce that. Fixed now; `<dfn ignore>` is properly *not* autolinkable and does *not* trigger an unused dfn complaint.

**Closed** 2020-07-27 19:32 UTC
Labels: enhancement, needs docs

**Comment by domenic** [comment] 2020-07-27 20:55
Confirmed working in https://github.com/whatwg/infra/pull/321; thanks!
