### ISSUE TITLE
Bikeshed picks the wrong term when multiple are present.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#786] opened 2016-08-12 08:01 UTC
Given the following:

```
<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing for.
Editor: Example Editor
Date: 1970-01-01
</pre>
<pre class=link-defaults>
spec:html; type:dfn; text:origin
</pre>
<pre class="anchors">
urlPrefix: https://example.com/spec/
    type: dfn
        text: local anchor
</pre>

<a>local anchor</a>
<a>origin</a>

<dfn>thing one</dfn>
<dfn for="thing one">one</dfn>
<dfn for="thing one">two</dfn>
<dfn for="thing one">local anchor</dfn>
<dfn for="thing one">origin</dfn>

<a>thing one</a>
<a for="thing one">one</a>
<a for="thing one">two</a>
<a for="thing one">local anchor</a>
<a for="thing one">origin</a>

<dfn>thing two</dfn>
<dfn for="thing two">one</dfn>
<dfn for="thing two">two</dfn>
<dfn for="thing two">local anchor</dfn>
<dfn for="thing two">origin</dfn>

<a>thing two</a>
<a for="thing two">one</a>
<a for="thing two">two</a>
<a for="thing two">local anchor</a>
<a for="thing one">origin</a>
```

every instance of `origin` links to "thing one"'s `origin`. I'd expect the bare `origin` to link to HTML, due to the `link-defaults` block, and the other instances to link to the local property definitions.

**Comment by tabatkins** [comment] 2016-08-16 23:36
Note that the second "origin" link also specifies `for="thing one"`, so *that* linking to thing one's origin is no mystery. ^_^

The bare `<a>origin</a>` linking to one of the local ones is expected behavior (or rather, it's not a bug in the way Bikeshed is currently intended to work).  Bikeshed *always* defaults to local links first; a search for a local "origin" succeeds, so it returns immediately.  Only after that does it try for a foreign anchor and apply link-defaults (which, by their nature, talk about foreign anchors).  To get this to work as you want, you need to force it to fail to find a local link with `for="/"`, indicating that you *require* a definition without a `for` value (rather than just not caring about a `for` value, as the lack of an attribute indicates).

It *is* weird that you didn't get a link error for `<a>origin</a>` complaining that there were multiple possible targets, and it was arbitrarily choosing one.  Or is that what happened, and you just omitted it?

**Comment by mikewest** [comment] 2016-08-18 09:49
> The bare `<a>origin</a>` linking to one of the local ones is expected behavior 

Interesting. Changing this to `<a for="/">origin</a>` gives me:

```
LINK ERROR: Multiple possible 'dfn' local refs for 'local anchor'.
Arbitrarily chose the one with type 'dfn' and for ''.
LINK ERROR: Multiple possible 'dfn' refs for 'origin'.
Arbitrarily chose the one in html.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:html; type:dfn; text:origin
spec:html; type:dfn; text:origin
spec:html; type:dfn; text:origin
 ✔  Successfully generated, with 2 linking errors
```

I assume this is due to weirdness in the HTML spec? There are several `<dfn>Origin</dfn>` in that document, but only one is exported, so I'd hoped it would Just Work.

**Comment by domenic** [comment] 2016-08-19 20:05
We're getting more reports of it not preferring local links in https://github.com/w3c/webappsec-referrer-policy/pull/64/files/1b4d2957abaf4d4f7f1189b920e7ead847fc88a0..6c8d24d7203cf81a24f748112f77cea2bae08b60#r75542122, with it getting confused and linking to HTML instead whenever you define two things with the same text, even if one of them has for="". I've run into this several times.

@tabatkins, I think Bikeshed is either not working as you planned, or the way that Bikeshed works here is just too confusing for humans to use.

**Comment by jyasskin** [comment] 2016-08-22 20:43
> There are several `<dfn>Origin</dfn>` in that document, but only one is exported, so I'd hoped it would Just Work.

`spec:html; type:dfn; text:origin` in the sample's `link-defaults` says to link to HTML's `<dfn>origin</dfn>` whether or not it's exported. The fact that HTML has multiple "/origin" dfn-type definitions is a problem. IIRC, two of them need `for` values (request and url), and one needs an `http-header` type.

You can distinguish between HTML's  `<dfn>origin</dfn>` and the local spec's `<dfn for="thing one">origin</dfn>` by writing:

```html
<pre class=link-defaults>
spec:html; type:dfn; text:origin; for: /
</pre>
```

I do think there should be a better way to say "the default `for` for this text is '/'", to let Bikeshed distinguish between pulling in an additional `for` value from another spec vs setting the default `for` value for the local spec to use.

**Comment by tabatkins** [comment] 2016-08-22 20:48
Yeah, there should be, and the handling of cases like HTML's origin is definitely slightly broken right now.

**Comment by tabatkins** [comment] 2016-08-22 20:50
@domenic I'm gonna put this family of errors at the top of my to-do list.  I won't be able to work on it this week (moving into a new house), but will get it ASAP.

**Comment by jyasskin** [comment] 2016-08-23 17:11
This is worse than I thought: 

```html
<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing for.
Editor: Example Editor
Date: 1970-01-01
</pre>
<pre class=link-defaults>
spec:html; type:dfn; text:environment-settings-object; for:/
</pre>

<p><a>environment settings object</a>
<p><a for=/>environment settings object</a>
<p><a for=quux>environment settings object</a>

<p><dfn for=quux>environment settings object</dfn>
```

yields

```html
   <p><a data-link-type="dfn" href="#quux-environment-settings-object">environment settings object</a> </p>
   <p><a data-link-type="dfn" href="https://html.spec.whatwg.org/multipage/webappapis.html#environment-settings-object">environment settings object</a> </p>
   <p><a data-link-type="dfn" href="#quux-environment-settings-object">environment settings object</a> </p>
   <p><dfn data-dfn-for="quux" data-dfn-type="dfn" data-noexport="" id="quux-environment-settings-object">environment settings object<a class="self-link" href="#quux-environment-settings-object"></a></dfn> </p>
```

with no warnings at all. Note that the `<a>environment settings object</a>` completely ignores the `link-defaults` section's request to default to `for=/`.

**Comment by tabatkins** [comment] 2016-09-02 00:30
Okay, looking into this, it's all Bikeshed working "as intended". The "intended" isn't great, tho.

Domenic's issue is that (a) I always prefer local refs over remote refs, to avoid surprise, and (b) I want to prefer `<pre class=anchors>` over remote refs, for the same reason (you wouldn't put them in the block if you didn't want to link to them). I *implemented* (b) by classifying anchor-block refs as "local".  It looks like this is causing a significant amount of confusion, tho. I think the right solution is to create a third priority level, so `local > anchor-block > remote`.

I'll work on this first, then try to decipher Mike's further issue.

**Comment by tabatkins** [comment] 2016-10-20 00:33
Oh! I did this a little while ago. anchor-block refs are now preferred after locals, but before remotes, and they pay attention to link-defaults. I'll see if this fixes the examples in this thread tomorrow; I'm heading home now.

**Comment by tabatkins** [comment] 2016-10-27 22:58
Okay, so I'm closing this:

* Domenic's issue was fixed by me separating out anchor-block refs from local refs (and letting link-defaults apply to them)
* Mike's issue was a combination of slight confusion about how a for-less autolink worked (just doesn't care about `for`, rather than actively preferring an empty `for`), and HTML's markup being kinda messed up. The latter is fixed.
* Jeremy's issue was the same slight confusion.

So it looks like everything's fine, since that "slight confusion" is a pretty basic part of how Bikeshed's autolinking works and is necessary for it to work without requiring people to specify a `for` value in lots of unambiguous cases.

**Closed by tabatkins** 2016-10-27 22:59 UTC

**Comment by domenic** [comment] 2016-10-27 23:01
Wait, but I thought per the discussion in https://github.com/w3c/ServiceWorker/pull/995#issuecomment-256487189, it was possible to use link-defaults to override things so that `<a>environment settings object</a>` goes to HTML's? That is, so that for-less autolinks go to whatever's in link-defaults with `for: /`? I think a lot of us would like that, and now I'm confused as to whether or not it's supported.
