### ISSUE TITLE
Markdown inside `[=...=]`.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#1006] opened 2017-04-27 07:47 UTC
For definitions like https://html.spec.whatwg.org/#concept-document-window, I'd like to link it as "associated `Document`" to mark the interface up appropriately inside the link. I'd hoped that ``[=asociated `Document`=]`` would do the trick, but it doesn't end up getting processed the way I'd expected. Perhaps we could strip those out of the string before comparing it to known definitions?

**Comment by mikewest** [comment] 2017-04-27 07:51
That is, ``[=associated `Document`=]`` would ideally have the same behavior as ``<a>associated `Document`</a>``.

**Comment by tabatkins** [comment] 2017-04-27 17:20
Sigh, yeah, this is part of the "all the shorthands don't *actually* nest properly" problem I've had since the beginning.  I only look for shorthands within a single given text node: if the two shorthands happen to be processed in the right order (outer first), both will be recognized; if not, the inner one will break up the surrounding shortcut's begin/end markers into separate text nodes, so it won't get recognized.

This is definitely something I need to fix, but it's also fairly non-trivial. :(

**Comment by tabatkins** [comment] 2017-04-27 17:45
Closing as a duplicate of #832.

**Closed by tabatkins** 2017-04-27 17:45 UTC
