### ISSUE TITLE
Can’t generate Web Audio API spec with current Bikeshed

### ISSUE THREAD

**Issue by sideshowbarker** [tabatkins/bikeshed#1631] opened 2020-03-26 12:26 UTC
When trying to generate output from https://webaudio.github.io/web-audio-api/index.bs, I get:

```
$ bikeshed spec index.bs index.html
WARNING: Multiple elements have the same ID 'dom-decodeerrorcallback-error'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-decodesuccesscallback-decodeddata'.
Deduping, but this ID may not be stable across revisions.
Traceback (most recent call last):
  File "/usr/local/bin/bikeshed", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bikeshed/cli.py", line 211, in main
    handleSpec(options, extras)
  File "/usr/local/lib/python3.7/site-packages/bikeshed/cli.py", line 247, in handleSpec
    doc.preprocess()
  File "/usr/local/lib/python3.7/site-packages/bikeshed/Spec.py", line 105, in preprocess
    self.processDocument()
  File "/usr/local/lib/python3.7/site-packages/bikeshed/Spec.py", line 197, in processDocument
    formatArgumentdefTables(self)
  File "/usr/local/lib/python3.7/site-packages/bikeshed/unsortedJunk.py", line 1245, in formatArgumentdefTables
    die("Can't find the '{0}' argument of method '{1}' in the argumentdef block.", argName, method.fullName, el=table)
AttributeError: 'InterfaceMember' object has no attribute 'fullName'
```

**Comment by tabatkins** [comment] 2020-03-26 17:23
Dupe of #1625 (which is also now fixed)

**Closed by tabatkins** 2020-03-26 17:23 UTC
