### ISSUE TITLE
Regression: Encoding Standard

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1537] opened 2019-10-09 10:19 UTC
TextDecoderCommon defines `encoding` twice, once as dfn and once as attribute. This used to work fine as you can see at https://encoding.spec.whatwg.org/#textdecoder-encoding (dfn) and https://encoding.spec.whatwg.org/#dom-textdecoder-encoding (attribute). It now fails on master https://travis-ci.org/whatwg/encoding/builds/595542510 with

> FATAL ERROR: Multiple local 'attribute' &lt;dfn>s for 'TextDecoderCommon' have the same linking text 'encoding'.

Interestingly enough, this still worked yesterday as the PR I created for this did not report this error, which strongly suggests Bikeshed is the culprit here.

**Comment by tabatkins** [comment] 2019-10-09 14:32
Hmmmm, nothing broke when I tested the changes yesterday, which is interesting. I'll look into this shortly.

**Comment by npm1** [comment] 2019-10-09 21:22
Dupe of https://github.com/tabatkins/bikeshed/issues/1536. It is certainly bikeshed BTW because this happened after I did bikeshed update to reproduce the build failure in my spec. There was a suggested culprit there, can we look to see if reverting that fixes the problems? This seems to affect a lot of specs.

**Comment by tabatkins** [comment] 2019-10-09 22:36
Yup, dupe.

**Comment by tabatkins** [comment] 2019-10-10 15:55
(Re-closing because this is still a dupe.)

**Closed by tabatkins** 2019-10-10 15:55 UTC
