### ISSUE TITLE
DataLossWarning coercing non-XML name

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1728] opened 2020-07-09 18:19 UTC
The latest build of WebAudio is producing warnings like:

```
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/html5lib/_ihatexml.py:257: DataLossWarning: Coercing non-XML name
  warnings.warn("Coercing non-XML name", DataLossWarning)
```

Don't know what the non-XML name is, but you can find the Travis results here:  https://travis-ci.com/github/WebAudio/web-audio-api/builds/174859937

We can probably get WebAudio to ignore these, but I thought you might like to know.  This wasn't happening a couple of days ago.

**Comment by tabatkins** [comment] 2020-07-09 18:25
You absolutely shouldn't ignore it, because it's a markup error and your output is mangled in some way now. ^_^

This is a *very* frustrating error, because the underlying parsing library I'm using (html5lib) has all the information it needs to output a useful error message to help you find the error, but it just... doesn't. I have a manually hacked-up version on my personal machine that does output a slightly more useful error message.

Anyway, this is usually caused by the someone breaking a tag with a lot of attributes across lines, and putting the closing `>` on a line on its own. A line-starting `>` character is Markdown for "blockquote", which currently gets recognized before the HTML parser has a chance to run over the text, so you're left with an unclosed tag (which then immediately sees an attribute named `<blockquote`, which triggers the error as that's an invalid attribute name).

I'm part-way thru writing my own HTML parser right now, partially so I can catch these errors and say something more useful. For now, I suggest checking for line-starting `>` characters, or unclosed attributes, coming from a recent patch.

**Closed by tabatkins** 2020-07-09 18:25 UTC

**Comment by rtoy** [comment] 2020-07-10 15:58
Thanks, I'll look into it.  I look forward to a new version that prints out better error messages.

**Comment by rtoy** [comment] 2020-07-14 15:01
For the record, this was caused by a missing closing quote on an href url. Something like:
```
<a href="url>stuff</a>
```
