### ISSUE TITLE
link-defaults suggestion does not help fix the multiple possible refs warning

### ISSUE THREAD

**Issue by andypaicu** [tabatkins/bikeshed#1337] opened 2018-08-21 14:19 UTC
Hello

I'm currently building the CSP spec and I'm getting this warning:
<pre>LINK ERROR: Multiple possible 'ping' element-sub refs for 'a'.
Arbitrarily chose https://svgwg.org/svg2-draft/linking.html#AElementPingAttribute
To auto-select one of the following refs, insert one of these lines into a &lt;pre class=link-defaults&gt; block:
spec:html; type:element-attr; text:ping
spec:svg2; type:element-attr; text:ping
<{a/ping}></pre>

I want to auto-select the html ref in this case so I figured I can follow the suggestion.

The spec already has a `<pre class=link-defaults>` element but no matter how much I try the warning does not go away (and the svg link is auto-selected).

I've tried adding it on its own line:
<pre>spec:html; type:element-attr; text:ping</pre>

I've tried inserting it into the already existing structure:
<pre>
spec:html
  type: dfn
    text: applet
    text: case-sensitive
    text: browsing context; for: /
    text: plugin document
    text: fallback base url
    text: duplicate-attribute
    text: origin; for: /
  type: element
    text: a
    text: a/ping
    text: link
    text: script
    text: style
  <b>type: element-attr
    text: ping</b>
spec:fetch
  type: dfn
    text: main fetch
    text: http-network fetch
    text: http fetch
    text: keepalive flag
    text: response; for: /
...</pre>

At this point it feels like I'm missing something simple or there is a bug here, or maybe the suggestion has not been updated when some change was made?

**Comment by tabatkins** [comment] 2018-08-21 15:10
That's almost certainly something wrong on my side. Thanks for reporting, I'll look into it.

**Comment by tabatkins** [comment] 2018-08-21 16:50
Ah, this is the same problem @annevk just ran into for a different spec - interesting coincidence!

So the problem *is* on my side, but you can fix it on your side too - just add `for:a` to the link-defaults line.

**Comment by tabatkins** [comment] 2018-08-21 19:41
Okay, fixed in 0c35a36.

I was checking if the `for` values from the default matched the link, and only doing so if the link did indeed contain a `for` value. This meant that if you didn't specify a `for` in your default (which, semantically, means "I don't care about the `for` value" everywhere else in Bikeshed), but did specify one in your link, it wouldn't match and the default wouldn't apply.  I've fixed it to only check the `for` values against each other when *both* the link and the default specify one.

This fixed a few regression tests in the testsuite, so it looks like it's working as intended.

**Closed by tabatkins** 2018-08-21 19:41 UTC

**Comment by andypaicu** [comment] 2018-08-22 10:57
Thank you can confirm it's fixed.
