### ISSUE TITLE
Couldn't download remote manifest file - CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by sandersaares** [tabatkins/bikeshed#1352] opened 2018-09-25 07:59 UTC
Following the documentation to install Bikeshed, the `bikeshed update` command fails:

```
C:\>bikeshed update
Updating via manifest...
WARNING: Couldn't download remote manifest file.
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
Falling back to a manual update...
Downloading anchor data...
FATAL ERROR: Either this version of the anchor-data API is no longer supported, or (more likely) there was a transient network error. Try again in a little while, and/or update Bikeshed. If the error persists, please report it on GitHub.
 ✘  Did not generate, due to fatal errors
```

This is in a Windows container with latest Windows 10 Enterprise. Python 2.7.15 and pip 9.0.3. All freshly installed.

What should I do?

**Comment by dascandy** [comment] 2018-12-12 09:44
Same error on Ubuntu 18.04, all freshly installed.

**Comment by dascandy** [comment] 2018-12-12 09:47
Problem is that it connects to api.csswg.org, which presents a Let's-Encrypt certificate which for some reason Python does not trust. All browsers trust it just fine. Some problem with Python's default trust store for fresh python installs?

**Comment by jakearchibald** [comment] 2020-04-07 07:22
I'm also getting this issue:

```
~/dev/bikeshed master
❯ bikeshed update
Updating via manifest...
WARNING: Couldn't download remote manifest file.
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
Falling back to a manual update...
Downloading anchor data...
FATAL ERROR: Couldn't download anchor data.  Error was:
Network error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
 ✘  Did not generate, due to fatal errors
```

**Comment by jakearchibald** [comment] 2020-04-07 08:00
Ah, there's a note in the docs:

> Note: If you’re on a Mac, bikeshed update might fail with some errors about certificates. This is a known issue with the version of Python 3.7 shipped with XCode, which might be the default on your system. To fix this, install Python 3.7 with Brew instead.

**Comment by tabatkins** [comment] 2020-04-10 17:54
Closing because the workaround is already in the docs, and with luck we'll get the issue fixed entirely once one of my dependencies updates.

**Closed by tabatkins** 2020-04-10 17:54 UTC

**Comment by plinss** [comment] 2020-04-11 02:56
@jakearchibald can you let me know what version of python you're using? I'm unable to reproduce this issue with any of the python3 binaries installed on my mac running 10.15.4 (including the one from xcode).

**Comment by sideshowbarker** [comment] 2020-04-11 04:08
I can reproduce it in my environment with this:

```
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/bin/python3
```

stack looks like this:

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
```

**Comment by sideshowbarker** [comment] 2020-04-11 04:18
Actually I get multiple tracebacks, including this:

```
  File "/Users/mike/workspace/bikeshed/bikeshed/update/updateBiblio.py", line 99, in getSpecrefData
    with closing(urllib.request.urlopen("https://api.specref.org/bibrefs")) as fh:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
```

…which shows the call from the Bikeshed code.

That’s from running `update --skip-manifest --biblio`

**Comment by plinss** [comment] 2020-04-11 04:39
Hm, well that last traceback isn't using json_home_client, it's actually using requests (which uses it's own ca bundle instead of the system bundle).

Not sure what's going on in the first traceback, not enough context. 

I still can't reproduce using the python on my machine at that path. macOS 10.15.4, latest Xcode 11.4 (11E146), I cloned the current bikeshed and setup a new venv using that python, so nothing else at play. What version of macOS and Xcode are you using?

**Comment by sideshowbarker** [comment] 2020-04-11 04:59
> Hm, well that last traceback isn't using json_home_client, it's actually using requests (which uses it's own ca bundle instead of the system bundle).

What exactly there indicates that it’s using requests? The call from the Bikeshed code is this:

```
with closing(urllib.request.urlopen("https://api.specref.org/bibrefs"))
```

**Comment by tabatkins** [comment] 2020-04-11 05:01
Yeah, that's definitely just urllib; it just happens to originate from the `urllib/request.py` file once it gets deeper than my call.

**Comment by plinss** [comment] 2020-04-11 05:03
What version of bikeshed are you using? The current code is:

bikeshed/update/updateBiblio.py(96):
    def getSpecrefData():
        try:
            return requests.get("https://api.specref.org/bibrefs").text
        except requests.exceptions.RequestException:

**Comment by sideshowbarker** [comment] 2020-04-11 05:03
> I still can't reproduce using the python on my machine at that path. macOS 10.15.4, latest Xcode 11.4 (11E146), I cloned the current bikeshed and setup a new venv using that python, so nothing else at play. What version of macOS and Xcode are you using?

* macOS 10.15.4 (19E287)
* Xcode 11.4 (11E146)

```
$ /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/bin/python3
Python 3.7.3 (default, Nov 15 2019, 04:04:52)
```

**Comment by tabatkins** [comment] 2020-04-11 05:10
> What version of bikeshed are you using?

Presumably the version from this morning, since I merged his fixes to use `requests` today. 😀

**Comment by plinss** [comment] 2020-04-11 05:11
Ah.

**Comment by sideshowbarker** [comment] 2020-04-11 05:13
> What version of bikeshed are you using?

Sorry for the confusion — to demonstrate the problem, I wasnt’t testing with the current code. Those tracebacks are with the code prior to today’s fix. Apologies for not being clear about with.

So with the current code from master, the only remaining calls that fail are json_home_client `APIClient` calls in `bikeshed/update/updateTestSuites.py` and `updateCrossRefs.py`:

```
Downloading test suite data...
FATAL ERROR: Couldn't download test suite data.  Error was:
Network error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
 ✘  Did not generate, due to fatal errors
```

Most-relevant traceback:

```
Traceback (most recent call last):
  File "bikeshed.py", line 5, in <module>
    bikeshed.main()
  File "/Users/mike/workspace/bikeshed/bikeshed/cli.py", line 210, in main
    handleUpdate(options, extras)
  File "/Users/mike/workspace/bikeshed/bikeshed/cli.py", line 238, in handleUpdate
    update.update(anchors=options.anchors, backrefs=options.backrefs, biblio=options.biblio, caniuse=options.caniuse, mdn=options.mdn, linkDefaults=options.linkDefaults, testSuites=options.testSuites, languages=options.languages, wpt=options.wpt, dryRun=constants.dryRun, force=options.force)
  File "/Users/mike/workspace/bikeshed/bikeshed/update/main.py", line 42, in update
    "testSuites": updateTestSuites.update(path=path, dryRun=dryRun) if testSuites else None,
  File "/Users/mike/workspace/bikeshed/bikeshed/update/updateTestSuites.py", line 16, in update
    shepherd = APIClient("https://api.csswg.org/shepherd/", version="vnd.csswg.shepherd.v1")
  File "/Library/Python/3.7/site-packages/json_home_client-0.0.0-py3.7.egg/json_home_client/client.py", line 247, in __init__
  File "/Library/Python/3.7/site-packages/json_home_client-0.0.0-py3.7.egg/json_home_client/client.py", line 269, in _load_home
  File "/Library/Python/3.7/site-packages/json_home_client-0.0.0-py3.7.egg/json_home_client/client.py", line 326, in _request
json_home_client.client.NetworkError: Network error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
```
…and the most-relevant part of that is this:
```
  File "/Users/mike/workspace/bikeshed/bikeshed/update/updateTestSuites.py", line 16, in update
    shepherd = APIClient("https://api.csswg.org/shepherd/", version="vnd.csswg.shepherd.v1")
```

…and the full set of tracebacks is this:

```
Downloading test suite data...
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/json_home_client-0.0.0-py3.7.egg/json_home_client/client.py", line 321, in _request
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bikeshed.py", line 5, in <module>
    bikeshed.main()
  File "/Users/mike/workspace/bikeshed/bikeshed/cli.py", line 210, in main
    handleUpdate(options, extras)
  File "/Users/mike/workspace/bikeshed/bikeshed/cli.py", line 238, in handleUpdate
    update.update(anchors=options.anchors, backrefs=options.backrefs, biblio=options.biblio, caniuse=options.caniuse, mdn=options.mdn, linkDefaults=options.linkDefaults, testSuites=options.testSuites, languages=options.languages, wpt=options.wpt, dryRun=constants.dryRun, force=options.force)
  File "/Users/mike/workspace/bikeshed/bikeshed/update/main.py", line 42, in update
    "testSuites": updateTestSuites.update(path=path, dryRun=dryRun) if testSuites else None,
  File "/Users/mike/workspace/bikeshed/bikeshed/update/updateTestSuites.py", line 16, in update
    shepherd = APIClient("https://api.csswg.org/shepherd/", version="vnd.csswg.shepherd.v1")
  File "/Library/Python/3.7/site-packages/json_home_client-0.0.0-py3.7.egg/json_home_client/client.py", line 247, in __init__
  File "/Library/Python/3.7/site-packages/json_home_client-0.0.0-py3.7.egg/json_home_client/client.py", line 269, in _load_home
  File "/Library/Python/3.7/site-packages/json_home_client-0.0.0-py3.7.egg/json_home_client/client.py", line 326, in _request
json_home_client.client.NetworkError: Network error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
```

**Comment by sideshowbarker** [comment] 2020-04-11 05:32
For the record here, the following are some related issues and bug reports

https://stackoverflow.com/q/57630314/441757 & https://stackoverflow.com/a/60334957/441757

https://github.com/HandBrake/HandBrake/issues/2216#issuecomment-527114519:

> Apple will not fix this, because Apple does not think this is a problem. The reply from Apple is
> 
> > the problem behaves as intended.
> > certifi is a third-party module, not part of Python itself.
> > urllib is a low-level library. It can handle ssl, but you must explicitly set up the SSL context with a cafile.
> > Try the following instead:
> > `pip3 install requests `
> > `python -c 'import requests; print(requests.get("https://apple.com").text)'`
> > If you only want to get cacert.pem, you can use "pip3 install certifi", but you must still explicitly pass cafile to urllib.

https://openradar.appspot.com/7111585
